### ISSUE TITLE
Soru: Yeni üniversite'yi nasıl test edip pr açabilirim?

### ISSUE THREAD

**Issue by muratbsts** [cagataycali/university-news-notifier#1]
Merhaba, Anadolu Üniversitesi'ni ekledim.

Bot adı: **anadoluuniversity_bot**

Repo: https://github.com/muratbsts/university-news-notifier

[tests/anadolu-test.js](https://github.com/muratbsts/university-news-notifier/blob/master/tests/anadolu-test.js) yi test ettiğimde scrape sonuçları getirebildi. Fakat botu başlattığımda hiç bir haber gelmedi. Haber gelmesi için yeni bir haber eklenmesini mi beklemeliyiz?

Deploy icin kendi forkumu template olarak kullandım. Bu konuda doğru yapıp yapmadığımdan emin olamadım. Eğer doğru yapmışsam pr açmak istiyorum.

**Comment by cagataycali** [comment]
Merhabalar,
Kendi fork'unuzu deploy olarak kullanabilirsiniz, bu sadece size o commit'deki aracın özelliklerini sunar
Kendi fork'unuzu master ile birleştirdim ve end to end test ekledim, bu sayede telegram'da test etmeden direkt olarak terminalde çıktıyı görebileceksiniz.
[![asciicast](https://asciinema.org/a/dsski0ddbmnh59i7mrqgc57bs.png)](https://asciinema.org/a/dsski0ddbmnh59i7mrqgc57bs)

Teşekkür ederim araca Anadolu Üniversitesini kazandırdığınız için,
Çağatay

**Comment by maliayas** [comment]
Bravo gençler. Böyle hobi çalışmaları insana meslek tutkusu kazandırıyor. JS uzmanı değilim ancak depoyu (repo) başarılı buldum. Kolay gelsin.

**Comment by cagataycali** [comment]
Çok teşekkür ederiz hocam, açık kaynağa katkıda bulunmaya çalışıyoruz. Sadece tüketici olarak bir ilerleme yaratamazdık.
