### ISSUE TITLE
Faydalı rss'ler olmalı mı?

### ISSUE THREAD

**Issue by cagataycali** [cagataycali/university-news-notifier#6]
<img width="552" alt="screen shot 2017-05-30 at 01 35 03" src="https://cloud.githubusercontent.com/assets/9213230/26563287/866496c8-44d8-11e7-9647-e241b75bb630.png">

Üniversiteler dışında başka yerel, yabancı kaynakların beslemelerine yer verilmeli mi size?
Üniversite öğrencilerinin takip edebileceği güzel birkaç kaynağı örnek olması amacıyla ekledim, fikirlerinize göre düzenleyebiliriz

**Comment by mstfknn** [comment]
rss i kullanıcı kendi ekleyebilmeli, ilgi alanına göre

**Comment by cagataycali** [comment]
Bot üzerinden mi eklenebilmeli yoksa json'u ekleyip pushlaması şeklinde bir onay sürecinden mi geçmeli. Sonuçta herkese gösterilecek bu liste

**Comment by mstfknn** [comment]
kişi kendi botuna ekleyebilmeli?

**Comment by pleycpl** [comment]
Rss ekleme, Bot uzerinde olsa cok iyi olur, usenirler json yazmaya :))

**Comment by cagataycali** [comment]
Eğer bot üzerinden ekleme yapılırsa, her clone'da başka bir sunucuda eklenen rss'ler ana kod ile bağımsız büyüyecek.

**Comment by muratbsts** [comment]
Bence üniversite haricinde bir şey eklememek lazım diye düşünüyorum. Üniversitenin sosyal medya hesapları vs olsun tabi ama Hackernews Reddit gibi platformlar başka bir bot'un konusu olsa daha güzel olmaz mı? Örneğin bu konuda kullandığım [hooks_bot](https://telegram.me/hooks_bot) var.

**Comment by cagataycali** [comment]
Tartışma sonucu olarak, üniversite haberleri ile sınırlı bir bot olması kararlaştırıldı.
