### ISSUE TITLE
Üniversitelerin kendi twitter hesaplarınıda takip etmek güzel olabilir?

### ISSUE THREAD

**Issue by mstfknn** [cagataycali/university-news-notifier#7]

**Comment by pleycpl** [comment]
<p>Cok iyi olur, Belki botta secenek sunariz, haberleri nerden istiyorsun rss mi? twitter mi? yoksa websiteden mi(tabi universitenin jsoni varsa, yoksa kendin json olusturucaksin.)? </p>

**Comment by cagataycali** [comment]
Aktif olmadığı için kapatıyorum.
